// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: auzbynhwadrrgbtxdrbs

class SupabaseConfig {
  static const String supabaseUrl = 'https://auzbynhwadrrgbtxdrbs.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1emJ5bmh3YWRycmdidHhkcmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4ODYyMjAsImV4cCI6MjA4MzQ2MjIyMH0.9AdMrymrG4Ix0dlJtQgIZM2dBe9b8WzPPzmZpnXNfcg';
}
